/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.crud;

import entidades.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian A. Candioti
 */
public class ProveedoresAgregarBaseDatos1 extends javax.swing.JPanel {

    /**
     * Creates new form UsuariosAgregarBaseDatos
     */
    public ProveedoresAgregarBaseDatos1() {
        initComponents();
        jTextFieldID.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNotas = new javax.swing.JTextArea();
        jTextFieldID = new javax.swing.JTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Nombre");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Notas");

        jTextAreaNotas.setColumns(20);
        jTextAreaNotas.setLineWrap(true);
        jTextAreaNotas.setRows(5);
        jTextAreaNotas.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaNotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    //Metodo para setear los valores del cliente en las celdas
    public void modificacionPrueba(Cliente aux) {
        try {
            jTextFieldID.setText(String.valueOf(aux.getId()));
            jTextFieldNombre.setText(aux.getNombre());
            jTextFieldApellido.setText(aux.getApellido());
            jTextFieldNDocumento.setText(String.valueOf(aux.getDocumento()));
            jTextFieldEmail.setText(aux.getEmail());
            jTextFieldNWhatsApp.setText(aux.getWhatsapp());
            jTextFieldLocalidad.setText(aux.getLocalidad());
            jTextFieldDireccion.setText(aux.getDireccion());
            jTextAreaNotas.setText(aux.getNotas());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error -Clase: UsuariosAgregarBaseDatos - metodo: modificacionPrueba()");
        }
    }

    public Cliente retornarCliente() {
        try {
            Cliente aux = new Cliente();
            aux.setId(Integer.parseInt(jTextFieldID.getText()));
            aux.setNombre(jTextFieldNombre.getText());
            aux.setApellido(jTextFieldApellido.getText());
            aux.setDocumento(Integer.parseInt(jTextFieldNDocumento.getText()));
            aux.setEmail(jTextFieldEmail.getText());
            aux.setWhatsapp(jTextFieldNWhatsApp.getText());
            aux.setLocalidad(jTextFieldLocalidad.getText());
            aux.setDireccion(jTextFieldDireccion.getText());
            aux.setNotas(jTextAreaNotas.getText());
            return aux;
        } catch (Exception e) {
            System.out.println("Error en el metodo retornarCliente() en la clase UsuariosAgregarBaseDeDatos");
        }
        return null;
    }

    public Cliente retornarCLienteAgregar() {
        try {
            String nombre = jTextFieldNombre.getText();
            String apellido = jTextFieldApellido.getText();
            int documento = Integer.parseInt(jTextFieldNDocumento.getText());
            String email = jTextFieldEmail.getText();
            String whatsapp = jTextFieldNWhatsApp.getText();
            String localalidad = jTextFieldLocalidad.getText();
            String direccion = jTextFieldDireccion.getText();
            String notas = jTextAreaNotas.getText();
            return new Cliente(nombre, apellido, documento, email, whatsapp, localalidad, direccion, notas);
        } catch (Exception e) {
            System.out.println("Error en el metodo retornarCLienteAgregar() de la clase usuariosAgregarBaseDatos");
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNotas;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
